### ISSUE TITLE
Model misunderstanding prompt format.

### ISSUE THREAD

**Issue by AeliusSaionji** [jdrbc/podly_pure_podcasts#18]
Amusingly, my llm doesn't seem to understand the prompt. I copied the ollama snippet given in the readme, and am using all default config options.
The readme suggested this model, so that's the one I'm using: `phi3:14b-medium-4k-instruct-q5_K_M`.

Not sure what to do here. Might make sense sanitize the input on podly's end. It might be easy to get any model to include JSON as part of its response, but apparently it's not quite so easy to make it only speak JSON.

> `Oct 18 15:11:52 reServer podly[2388074]: ERROR:global_logger:Error parsing ad segment: Extra data: line 1 column 49 (char 48) for` {"ad_segments": [36.6, 48.1], "confidence": 0.9}. Note: Although there are segments related to ads for IBM and a podcast (Breakfast Club), the instruction only asks for excerpts that are classified as advertisements featuring promotions or other network"s shows, which is why the IBM segment has been included with high confidence due to it being an explicit promotion.

> `Oct 18 15:11:52 reServer podly[2388074]: ERROR:global_logger:Error parsing ad segment: Extra data: line 1 column 101 (char 100) for` {"ad_segments": [1111.7, 1114.8, 1116.4, 1118.2, 1119.5, 1121.0, 1123.2, 1125.2], "confidence": 0.7}. Note: Advertisements in the above podcast excerpt are identified with a moderate level of confidence due to their promotional nature, but not being from within the core content (i.e., discussing the movie or artwork) which suggests these segments could be advertising AI services by IBM, rather than directly selling products or existing network shows.

**Comment by frrad** [comment]
There are already some hacks in place to transform the model output into actual JSON https://github.com/jdrbc/podly_pure_podcasts/blob/062dfd492f1ae714aa8d6a9fc67196e15836c23c/src/podcast_processor/podcast_processor.py#L259-L264 - it would be easy enough to extend that to something that would handle these output as well. That seems like a pretty reasonable tradeoff to me though it might be time to break out that code and maybe add some tests. What do you think @jdrbc ?

Longer term, I think it would be nicer to force the model output to adhere to a schema. 

* OpenAI has structured outputs https://openai.com/index/introducing-structured-outputs-in-the-api/
* It seems like ollama has "JSON Mode" https://github.com/ollama/ollama/blob/main/docs/api.md#json-mode which can guarantee that the output is _some_ valid JSON. It seems like it doesn't guarantee adherence to a particular schema though.
* This issue https://github.com/ollama/ollama/issues/6237 makes it seem like particular-schema support is coming to ollama potentially soon. Apparently they already support general grammars internally and it's just a matter of them doing the plumbing to expose more fine-grained control.
