### ISSUE TITLE
Separation of transcription and scoring openai clients

### ISSUE THREAD

**Issue by xerootg** [jdrbc/podly_pure_podcasts#24]
Hey! For a while, I've been running a fork of this wonderful tool, and it's great to see the maturity of it overall grow. I'm using gemma2 on ollama and faster-whisper-server to run the backend with great results. I've got a mildly tweaked system message which has given me great results with gemma2 for 3ish weeks now, and I'd like to contribute that back. However, the issue of faster-whisper-server - the mode is hardcoded to Whisper-1 and shares an openai client with the scoring half, meaning one API base, meaning I need to run a reverse proxy in addition to ollama, faster-whisper-server and podly_pure_podcasts. Is there a reason you have one openai client for both transcription and scoring? Are you opposed to a PR that would separate the two if a custom whisper server is provided? There's some other tweaks I have in my fork of faster-whisper-server that would probably be good to handle in podly instead, so others who are also running their own wisper instance can use this.

**Comment by jdrbc** [comment]
Hey! That sounds awesome. I've no objections to two clients. @frrad has done some abstraction on the transcription portion to support local & remote. Also possible to add a third implementation of Transcriber if it's not so easy to just drop in replace the open ai client.

**Comment by xerootg** [comment]
So I guess that's why I ask. I'm using `RemoteWhisperTranscriber` right now, but like, it shares a client. I think a third client, like `RemoteFasterWhisperServerTranscriber` would be cool, which if like a bool like `use_faster_whisper: True` was set would use. The current `RemoteWhisperTranscriber` assumes that your using `Whisper-1` a.k.a. the model that openai hosts. but it's entirely unnecessary. I'm also a *python hack*, not dev, so I'm not entirely clear what guidance there is around what the right approach is. I could see `RemoteWhisperTranscriber`'s constructor just checking if `use_faster_whisper is True` and if it is, make a client, otherwise set the class instance equal to the one from the root? It would be just a simple config manager change to default to `Whisper-1` if not set, so that's less of an issue than having a second api host. For some insight into what I have to work with, checkout the huge config I dropped in #16

**Comment by xerootg** [comment]
also, ollama is compatible with openai's api, but they have their own entire api surface too.

**Comment by frrad** [comment]
If it was me what I would do is 

1. Introduce two new variables in the config similar to these
  https://github.com/jdrbc/podly_pure_podcasts/blob/4170c92981c25a9b070e055a3b3e32c2d438c644/src/shared/config.py#L24-L25

    called something like `transcription_api_key` and `transcription_base_url`

1. Pipe them around to where we instantiate the `RemoteWhisperTranscriber`

 
     https://github.com/jdrbc/podly_pure_podcasts/blob/4170c92981c25a9b070e055a3b3e32c2d438c644/src/podcast_processor/podcast_processor.py#L62

1. Change around `RemoteWhisperTranscriber` to instantiate and own its own open AI client.


The only disadvantage I can see is that it makes configs a bit more verbose for people using remote whisper as they'll have to specify their API key twice, but I would personally prefer just having it be explicit instead of introducing more logic here.

Another option is if you wanted access to some faster-whisper specific API would be to create a new `FasterWhisperTranscriber` which subclasses the same `Transcriber` abstract class but does other things. Then you would add some logic near that same place

     https://github.com/jdrbc/podly_pure_podcasts/blob/4170c92981c25a9b070e055a3b3e32c2d438c644/src/podcast_processor/podcast_processor.py#L62


which would instantiate that instead of `LocalWhisper` or `RemoteWhisper` depending on the contents of the config.

**Comment by xerootg** [comment]
ok, so what about:
```python
class RemoteWhisperTranscriber(Transcriber):
    def __init__(self, logger: logging.Logger, config: Config):
        self.logger = logger
        self.remote_whisper_model = config.remote_whisper_model # whisper-1 vs... large-v3?
        self.faster_whisper_server = config.faster_whisper_server # bool, theres a quirk in faster_whisper_server's API vs openai

        # Use the openai config if no whisper config is provided
        base_url = config.whisper_base_url or config.openai_base_url
        api_key = config.whisper_api_key or config.openai_api_key

        self.openai_client = OpenAI(
            base_url=base_url,
            api_key=self.config.openai_api_key,
        )
```

```python
class Config(BaseModel):
    # meh, all the other stuff is unmodifiedish
    remote_whisper: bool = False
    whisper_api_key: Optional[str]
    whisper_base_url: Optional[str] = None 
    remote_whisper_model: str = "whisper-1" # openai model, use your own maybe
    whisper_language: str = "en"
    faster_whisper_server: bool = False # for quirks specific to the faster whisper server
    whisper_model: str = "base" # for local whisper
```

I'm gonna test this out for a bit, but if its no biggie to make a new client, then I will just do that. no need to duplicate things that aren't different that way?

**Comment by frrad** [comment]
This seems good. Depending on how many "quirks" there are, a separate` `Transcriber` could be preferable to a bunch of conditional logic in the `RemoteWhisperTranscriber` but 🤷 

You should open a PR! :) I think it's easier to go back and forth on that instead of code blocks in this issue.

**Comment by xerootg** [comment]
Ok, sounds good! I've been running my fork with basically this running for a couple weeks, I'll pr up whatever the rebased result is this weekend.

**Comment by mrbensley** [comment]
Hi @xerootg 

You mentioned you were getting great results using gemma2, but in my tests using gemma2, it's failing to detect all the ad segments. 

Just wondered what size model you're using and what your system prompt is?

**Comment by xerootg** [comment]
I've actually been having issues with gemma2 recently. I have a very different prompt, I'm still trying to tune it. I do a lot of segments like probably 20-30, and I use one of the 2b models with an 8k context. I'm starting to lean towards actually training a gemma2 based model with additional context baked in specifically for advertising. But hey, I'm just playing with this stuff, I don't actually know very much about it 😅

**Comment by mrbensley** [comment]
A custom trained model sounds like a great idea. It would be nice if there was someday a model specialised, efficient and small enough to run on a phone directly. 

Would splitting in to more segments make it harder for the language model to detect the overall flow of conversation and changes in topic? Particularly if an ad occurs over the transition between segments? 

My coding knowledge is virtually non-existent, so I don't really understand how Podly deals with this.

**Comment by xerootg** [comment]
I mean, it's just a conversation with an llm like chatgpt or copilot, except python is the one talking to the llm. But yeah. Basically, the prompt right now is a set of instructions and then a single example. I'd like to just layer on top of Gemma a conversation of other examples and then the system prompt becomes irrelevant, since it's baked into the model. Ollama makes it super easy, I just need more hours in the day lol.
 https://github.com/ollama/ollama/blob/main/docs/modelfile.md

**Comment by xerootg** [comment]
In this case, it doesn't have a memory, but you can seed something similar by baking a modelfile with conversation.

**Comment by frrad** [comment]
fixed by https://github.com/jdrbc/podly_pure_podcasts/pull/29
