### ISSUE TITLE
Variable mixup - documentation says OPENAI_BASE_API but program uses OPENAI_BASE_URL

### ISSUE THREAD

**Issue by bsharper** [jdrbc/podly_pure_podcasts#3]
The documentation says to set `OPENAI_BASE_API` but it appears that the code in `podcast_processor.py` is looking for `OPENAI_BASE_URL`. Couldn't figure out why my Groq key was being rejected until I checked the logs and saw an OpenAI error message.

Also I had to add the following to `config.yml` to get around a lookup error:
```yaml
podcasts:
  - "random_non_podcast"
 ```

Happy to provide more information if needed. Thanks!

**Comment by jdrbc** [comment]
thanks! should be fixed now
