### ISSUE TITLE
Enabling Whisper GPU acceleration

### ISSUE THREAD

**Issue by mrbensley** [jdrbc/podly_pure_podcasts#30]
Hey! I really appreciate the work that's been done on this project so far! 

I'm not a coder, but over the last few days I've managed to get Podly up and running, using 'llama-3.1-70b-versatile' through Groq (since it's free with a limit of 200,000 tokens per day). 

Originally I tried using various models through Ollama (llama3.1:8B, Mistral, phi3:14b), but I found the ad detection very poor with all of these smaller models, despite adding additional instructions and ad classification info to the system prompt. I saw that @xerootg had some success with Gemma2, so I'm interested to test that next. But for now, using Groq with a more powerful model seems to be working great. 

My question is: What's the best way to enable GPU acceleration for the Whisper transcription process? (Running on a PC with a Nvidia GPU with CUDA.) Perhaps we could add an option to enable this in the config file or something for users like me who aren't well-versed with Python?

**Comment by frrad** [comment]
I am using remote whisper but this

https://stackoverflow.com/a/77426542

Makes it seem like it should work automatically?

**Comment by xerootg** [comment]
Yeah, in a previous iteration of my private branch, I replaced whisper with faster whisper. Even on bare cpu, it's faster than whisper. It has some API differences to be aware of, specifically, you must enumerate the return of `transcribe(...)` to get it to actually process, as it's an iterator (?? I don't python much, maybe a generator?), but if you have an Nvidia GPU, that should just work. I dont and getting ctranslate2 working for rocm is a chore, and faster-whisper-server was pretty easy to graft into the rocm fork of ctranslate2. Same thing applies for the openapi call, technically, you can just make a llama (or choose your backend LLM library) instance in the transcription parser instead.

**Comment by mrbensley** [comment]
I managed to find a solution. 

Whisper wasn't detecting my GPU, so I had to install the CUDA version of PyTorch to the virtual environment. 
The transcription process is now almost 3X faster on my computer. 


https://pytorch.org/get-started/locally/

`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

**Comment by ConorIA** [comment]
> using 'llama-3.1-70b-versatile' through Groq (since it's free with a limit of 200,000 tokens per day)

Do you mind sharing the relevant portions of your config.yaml?
