### ISSUE TITLE
Discord link has expired

### ISSUE THREAD

**Issue by xerootg** [jdrbc/podly_pure_podcasts#35]
Hey! The discord link in the readme is dead it seems. I had no idea there was a discord!

**Comment by frrad** [comment]
Does this one work: https://github.com/jdrbc/podly_pure_podcasts/pull/26#issuecomment-2480648012

If so, mind sending a PR to update the README?

**Comment by xerootg** [comment]
Nope, that one is dead :(

**Comment by frrad** [comment]
https://discord.gg/FRB98GtF6N

maybe?

**Comment by xerootg** [comment]
Yup. https://github.com/jdrbc/podly_pure_podcasts/pull/36
