### ISSUE TITLE
Error trying to get podcast app to subscribe to the podly endpoint

### ISSUE THREAD

**Issue by reynold1** [jdrbc/podly_pure_podcasts#38]
I entered "http://127.0.0.1:5001/feed/1" into gpodder (v3.1.1.4) and I get the following error in the cmd window:

=====

Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv --python 3.12.8

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv install
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing dependencies from Pipfile.lock (3a7f2b)...

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv shell
Launching subshell in virtual environment...
Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

(podly_pure_podcasts-main-n1Rxt2gQ) C:\Users\Administrator\Desktop\podly_pure_podcasts-main>python src/main.py
Config:
 {
  "openai_api_key": "XXXXXXXXXX",
  "openai_base_url": "https://api.openai.com/v1",
  "openai_max_tokens": 4096,
  "openai_model": "gpt-4o",
  "openai_timeout": 300,
  "output": {
    "fade_ms": 3000,
    "min_ad_segement_separation_seconds": 60,
    "min_ad_segment_length_seconds": 14,
    "min_confidence": 0.8
  },
  "podcasts": null,
  "processing": {
    "system_prompt_path": "config/system_prompt.txt",
    "user_prompt_template_path": "config/user_prompt.jinja",
    "num_segments_to_input_to_prompt": 30
  },
  "server": null,
  "server_port": 5001,
  "threads": 1,
  "whisper": {
    "whisper_type": "local",
    "model": "base"
  },
  "remote_whisper": null,
  "whisper_model": null,
  "automatically_whitelist_new_episodes": true,
  "number_of_episodes_to_whitelist_from_archive_of_new_feed": 1
}
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\main.py:12: DeprecationWarning: deprecated
  if config.podcasts is None:
INFO  [waitress] Serving on http://0.0.0.0:5001
INFO  [global_logger] Fetching feed with ID: 1
INFO  [global_logger] Refreshing feed with ID: 1
INFO  [global_logger] Fetching feed from URL: https://feeds.megaphone.fm/ep-wswb
INFO  [global_logger] Feed with ID: 1 refreshed
INFO  [global_logger] Generating XML for feed with ID: 1
ERROR [app] Exception on /feed/1 [GET]
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\app\routes.py", line 122, in get_feed
    feed_xml = generate_feed_xml(feed)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\app\feeds.py", line 142, in generate_feed_xml
    items = [feed_item(post) for post in feed.posts]  # type: ignore[attr-defined]
             ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\app\feeds.py", line 118, in feed_item
    if os.path.isfile(post.processed_audio_path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _path_isfile: path should be string, bytes, os.PathLike or integer, not NoneType

=====

Not sure what I I'm doing wrong at this point ...

**Comment by frrad** [comment]
sorry, this is a bug I introduced recently. WIP fix here https://github.com/jdrbc/podly_pure_podcasts/pull/37. Will try to get it in tonight.

**Comment by frrad** [comment]
Should be fixed now. If you pull main and still see this please reopen.

**Comment by reynold1** [comment]
I replaced the two files that you updated but am now running into the following error:

=====

Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv --python 3.12.8

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv install
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing dependencies from Pipfile.lock (3a7f2b)...

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv shell
Launching subshell in virtual environment...
Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

(podly_pure_podcasts-main-n1Rxt2gQ) C:\Users\Administrator\Desktop\podly_pure_podcasts-main>python src/main.py
Config:
 {
  "openai_api_key": "XXXXXXXXXX",
  "openai_base_url": "https://api.openai.com/v1",
  "openai_max_tokens": 4096,
  "openai_model": "gpt-4o",
  "openai_timeout": 300,
  "output": {
    "fade_ms": 3000,
    "min_ad_segement_separation_seconds": 60,
    "min_ad_segment_length_seconds": 14,
    "min_confidence": 0.8
  },
  "podcasts": null,
  "processing": {
    "system_prompt_path": "config/system_prompt.txt",
    "user_prompt_template_path": "config/user_prompt.jinja",
    "num_segments_to_input_to_prompt": 30
  },
  "server": null,
  "server_port": 5001,
  "threads": 1,
  "whisper": {
    "whisper_type": "local",
    "model": "base"
  },
  "remote_whisper": null,
  "whisper_model": null,
  "automatically_whitelist_new_episodes": true,
  "number_of_episodes_to_whitelist_from_archive_of_new_feed": 1
}
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\main.py", line 4, in <module>
    from app.feeds import add_or_refresh_feed
  File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\app\feeds.py", line 102
    <title>podly_pure_podcasts/src/app/feeds.py at main · jdrbc/podly_pure_podcasts</title>
                                                                                           ^
SyntaxError: invalid character '·' (U+00B7)

(podly_pure_podcasts-main-n1Rxt2gQ) C:\Users\Administrator\Desktop\podly_pure_podcasts-main>

=====

Hopefully this is an easier error to fix!

**Comment by reynold1** [comment]
Opened a new issue related to syntax error in <title> content
