### ISSUE TITLE
Trouble with downloading episode and starting transcription process

### ISSUE THREAD

**Issue by reynold1** [jdrbc/podly_pure_podcasts#42]
I've made it farther in the process but now get the following error:

Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pip install pipenv
Requirement already satisfied: pipenv in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (2024.4.0)
Requirement already satisfied: certifi in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (2024.8.30)
Requirement already satisfied: packaging>=22 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (24.2)
Requirement already satisfied: setuptools>=67 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (75.6.0)
Requirement already satisfied: virtualenv>=20.24.2 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (20.28.0)
Requirement already satisfied: distlib<1,>=0.3.7 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from virtualenv>=20.24.2->pipenv) (0.3.9)
Requirement already satisfied: filelock<4,>=3.12.2 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from virtualenv>=20.24.2->pipenv) (3.16.1)
Requirement already satisfied: platformdirs<5,>=3.9.1 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from virtualenv>=20.24.2->pipenv) (4.3.6)

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv --python 3.12.8

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv install
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing dependencies from Pipfile.lock (3a7f2b)...

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv shell
Launching subshell in virtual environment...
Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

(podly_pure_podcasts-main-n1Rxt2gQ) C:\Users\Administrator\Desktop\podly_pure_podcasts-main>python src/main.py
Config:
 {
  "openai_api_key": "XXXXXXXXXX",
  "openai_base_url": "https://api.openai.com/v1",
  "openai_max_tokens": 4096,
  "openai_model": "gpt-4o",
  "openai_timeout": 300,
  "output": {
    "fade_ms": 3000,
    "min_ad_segement_separation_seconds": 60,
    "min_ad_segment_length_seconds": 14,
    "min_confidence": 0.8
  },
  "podcasts": null,
  "processing": {
    "system_prompt_path": "config/system_prompt.txt",
    "user_prompt_template_path": "config/user_prompt.jinja",
    "num_segments_to_input_to_prompt": 30
  },
  "server": null,
  "server_port": 5001,
  "threads": 1,
  "whisper": {
    "whisper_type": "local",
    "model": "base"
  },
  "remote_whisper": null,
  "whisper_model": null,
  "automatically_whitelist_new_episodes": true,
  "number_of_episodes_to_whitelist_from_archive_of_new_feed": 1
}
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> bae70e584468, empty message
INFO  [alembic.runtime.migration] Running upgrade bae70e584468 -> fa3a95ecd67d, audio processing paths
INFO  [alembic.runtime.migration] Running upgrade fa3a95ecd67d -> 770771437280, episode whitelist
INFO  [alembic.runtime.migration] Running upgrade 770771437280 -> 6e0e16299dcb, alternate feed ID
C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\main.py:12: DeprecationWarning: deprecated
  if config.podcasts is None:
INFO  [waitress] Serving on http://0.0.0.0:5001
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Fetching feed from URL: https://feeds.megaphone.fm/ep-wswb
INFO  [global_logger] Storing feed: Where Should We Begin? with Esther Perel
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Feed stored with ID: 1
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: 402cb0ac-abf4-11ee-a295-9324b7115017 to false
WARNI [waitress.queue] Task queue depth is 1
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: b2e2d894-a6e5-11ec-b512-7bcd20677c39 to true
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: fd14cfcc-a6e4-11ec-af02-6b0791dada7c to true
WARNI [waitress.queue] Task queue depth is 1
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: fd090f98-a6e4-11ec-af02-63e1365b7709 to true
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: d6ffef72-3003-11ec-8afc-47c33d75dc7d to true
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: d6de0a2e-3003-11ec-8afc-f7af41b89b7c to true
WARNI [waitress.queue] Task queue depth is 1
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: ea13e848-3003-11ec-897a-e3058f41fc20 to true
INFO  [global_logger] Setting whitelist status for post with GUID: d6bc4650-3003-11ec-8afc-ab6e9a46e4cf to true
WARNI [waitress.queue] Task queue depth is 1
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: e9f25188-3003-11ec-897a-2bdfcbd14ea8 to true
WARNI [waitress.queue] Task queue depth is 1
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: e9cfe17a-3003-11ec-897a-6be1990d6a02 to true
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: e9addada-3003-11ec-897a-ff736c4cbcf2 to true
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: d69a3bb4-3003-11ec-8afc-d74a25dabeb1 to true
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: d67844c8-3003-11ec-8afc-8b67cd23067d to true
WARNI [waitress.queue] Task queue depth is 1
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: d6569882-3003-11ec-8afc-87bc21216a52 to true
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: 6617f558-21d4-11ec-b1db-3bf6499b2287 to true
INFO  [global_logger] Setting whitelist status for post with GUID: ee78df62-21d3-11ec-a0b2-6f1bb6e02754 to true
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: f7a39062-aff3-11ea-bf55-3354380d551a to true
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: 3d77b60e-7516-11ea-b076-231ecdd7b9ed to true
WARNI [waitress.queue] Task queue depth is 1
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: 167bf34e-7516-11ea-bcfb-df177c704fcc to true
WARNI [waitress.queue] Task queue depth is 1
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: 14d8e098-7510-11ea-b7e6-e36df02ad461 to true
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: d84c50e6-6e03-11ea-ad31-cb3c817da903 to true
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: 934ee98f413f91fe6761de9c5345ac2b to true
WARNI [waitress.queue] Task queue depth is 1
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: 6f29b2e6fda4b799a6287a081cae1789 to true
WARNI [waitress.queue] Task queue depth is 1
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Setting whitelist status for post with GUID: bc6bd9444bf097a66090b632545b4885 to true
WARNI [waitress.queue] Task queue depth is 1
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Fetching feed with ID: 1
INFO  [global_logger] Refreshing feed with ID: 1
INFO  [global_logger] Fetching feed from URL: https://feeds.megaphone.fm/ep-wswb
INFO  [global_logger] Feed with ID: 1 refreshed
INFO  [global_logger] Generating XML for feed with ID: 1
INFO  [global_logger] XML generated for feed with ID: 1
INFO  [global_logger] Feed with ID: 1 fetched and XML generated
INFO  [global_logger] Fetching feed with ID: 1
INFO  [global_logger] Refreshing feed with ID: 1
INFO  [global_logger] Fetching feed from URL: https://feeds.megaphone.fm/ep-wswb
INFO  [global_logger] Feed with ID: 1 refreshed
INFO  [global_logger] Generating XML for feed with ID: 1
INFO  [global_logger] XML generated for feed with ID: 1
INFO  [global_logger] Feed with ID: 1 fetched and XML generated

===== [SNIP!!!] =====

INFO  [global_logger] request to download post with GUID: 6f29b2e6fda4b799a6287a081cae1789
INFO  [global_logger] Downloading post: Speak to Me in French
INFO  [shared.podcast_downloader] Downloading https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/chrt.fm/track/524GE/traffic.megaphone.fm/GLT1320575665.mp3?updated=1571169443 into in/Speak to Me in French/Speak to Me in French.mp3...
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): www.podtrac.com:443
DEBUG [urllib3.connectionpool] https://www.podtrac.com:443 "GET /pts/redirect.mp3/pdst.fm/e/chrt.fm/track/524GE/traffic.megaphone.fm/GLT1320575665.mp3?updated=1571169443 HTTP/11" 302 None
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): pdst.fm:443
DEBUG [urllib3.connectionpool] https://pdst.fm:443 "GET /e/chrt.fm/track/524GE/traffic.megaphone.fm/GLT1320575665.mp3?updated=1571169443 HTTP/11" 302 108
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): chrt.fm:443
DEBUG [urllib3.connectionpool] https://chrt.fm:443 "GET /track/524GE/traffic.megaphone.fm/GLT1320575665.mp3?updated=1571169443 HTTP/11" 302 0
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): traffic.megaphone.fm:443
DEBUG [urllib3.connectionpool] https://traffic.megaphone.fm:443 "GET /GLT1320575665.mp3?updated=1571169443 HTTP/11" 302 None
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): dcs-spotify.megaphone.fm:443
DEBUG [urllib3.connectionpool] https://dcs-spotify.megaphone.fm:443 "GET /GLT1320575665.mp3?key=ec99532e05e98da5a524523203728585&request_event_id=6568e249-44b8-4e6b-a8d8-adf8f87d869d&timetoken=1734234800_B6BD0D0CAADC0690980F4E0E11F4CC97 HTTP/11" 200 64004656
INFO  [shared.podcast_downloader] Download complete.
DEBUG [httpx] load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG [httpx] load_verify_locations cafile='C:\\Users\\Administrator\\.virtualenvs\\podly_pure_podcasts-main-n1Rxt2gQ\\Lib\\site-packages\\certifi\\cacert.pem'
ERROR [app] Exception on /post/6f29b2e6fda4b799a6287a081cae1789.mp3 [GET]
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\app\routes.py", line 81, in download_post
    output_path = processor.process(post)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(podcast_processor.podcast_processor.PodcastProcessor.process) at 0x19bcef067a0>", line 32, in process
  File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\podcast_processor\podcast_processor.py", line 84, in process
    classification_dir = self.make_dirs(post, processed_audio_path)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(podcast_processor.podcast_processor.PodcastProcessor.make_dirs) at 0x19bcef06840>", line 50, in make_dirs
  File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\podcast_processor\podcast_processor.py", line 121, in make_dirs
    os.makedirs(processed_audio_dir, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'srv/Where Should We Begin? with Esther Perel'

**Comment by frrad** [comment]
Interesting. This might be an issue with which filenames are allowed in windows. Can you try pulling my branch from https://github.com/jdrbc/podly_pure_podcasts/pull/43 and see if that fixes things.

**Comment by reynold1** [comment]
I just swapped out the revised "podcast_downloader.py" file like you suggested. I made it a little farther in the process but got stopped by what looks like a similar error:

=====

Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pip install pipenv
Requirement already satisfied: pipenv in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (2024.4.0)
Requirement already satisfied: certifi in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (2024.8.30)
Requirement already satisfied: packaging>=22 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (24.2)
Requirement already satisfied: setuptools>=67 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (75.6.0)
Requirement already satisfied: virtualenv>=20.24.2 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (20.28.0)
Requirement already satisfied: distlib<1,>=0.3.7 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from virtualenv>=20.24.2->pipenv) (0.3.9)
Requirement already satisfied: filelock<4,>=3.12.2 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from virtualenv>=20.24.2->pipenv) (3.16.1)
Requirement already satisfied: platformdirs<5,>=3.9.1 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from virtualenv>=20.24.2->pipenv) (4.3.6)

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv --python 3.12.8

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv install
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing dependencies from Pipfile.lock (3a7f2b)...

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv shell
Launching subshell in virtual environment...
Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

(podly_pure_podcasts-main-n1Rxt2gQ) C:\Users\Administrator\Desktop\podly_pure_podcasts-main>python src/main.py
Config:
 {
  "openai_api_key": "XXXXXXXXXX",
  "openai_base_url": "https://api.openai.com/v1",
  "openai_max_tokens": 4096,
  "openai_model": "gpt-4o",
  "openai_timeout": 300,
  "output": {
    "fade_ms": 3000,
    "min_ad_segement_separation_seconds": 60,
    "min_ad_segment_length_seconds": 14,
    "min_confidence": 0.8
  },
  "podcasts": null,
  "processing": {
    "system_prompt_path": "config/system_prompt.txt",
    "user_prompt_template_path": "config/user_prompt.jinja",
    "num_segments_to_input_to_prompt": 30
  },
  "server": null,
  "server_port": 5001,
  "threads": 1,
  "whisper": {
    "whisper_type": "local",
    "model": "base"
  },
  "remote_whisper": null,
  "whisper_model": null,
  "automatically_whitelist_new_episodes": true,
  "number_of_episodes_to_whitelist_from_archive_of_new_feed": 1
}
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\main.py:12: DeprecationWarning: deprecated
  if config.podcasts is None:
INFO  [waitress] Serving on http://0.0.0.0:5001
INFO  [global_logger] Fetching feed with ID: 1
INFO  [global_logger] Refreshing feed with ID: 1
INFO  [global_logger] Fetching feed from URL: https://feeds.megaphone.fm/ep-wswb
INFO  [global_logger] Feed with ID: 1 refreshed
INFO  [global_logger] Generating XML for feed with ID: 1
INFO  [global_logger] XML generated for feed with ID: 1
INFO  [global_logger] Feed with ID: 1 fetched and XML generated
INFO  [global_logger] request to download post with GUID: 6f29b2e6fda4b799a6287a081cae1789
INFO  [global_logger] Downloading post: Speak to Me in French
INFO  [shared.podcast_downloader] Downloading https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/chrt.fm/track/524GE/traffic.megaphone.fm/GLT1320575665.mp3?updated=1571169443 into in\Speak to Me in French\Speak to Me in French.mp3...
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): www.podtrac.com:443
DEBUG [urllib3.connectionpool] https://www.podtrac.com:443 "GET /pts/redirect.mp3/pdst.fm/e/chrt.fm/track/524GE/traffic.megaphone.fm/GLT1320575665.mp3?updated=1571169443 HTTP/11" 302 None
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): pdst.fm:443
DEBUG [urllib3.connectionpool] https://pdst.fm:443 "GET /e/chrt.fm/track/524GE/traffic.megaphone.fm/GLT1320575665.mp3?updated=1571169443 HTTP/11" 302 108
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): chrt.fm:443
DEBUG [urllib3.connectionpool] https://chrt.fm:443 "GET /track/524GE/traffic.megaphone.fm/GLT1320575665.mp3?updated=1571169443 HTTP/11" 302 0
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): traffic.megaphone.fm:443
DEBUG [urllib3.connectionpool] https://traffic.megaphone.fm:443 "GET /GLT1320575665.mp3?updated=1571169443 HTTP/11" 302 None
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): dcs-spotify.megaphone.fm:443
DEBUG [urllib3.connectionpool] https://dcs-spotify.megaphone.fm:443 "GET /GLT1320575665.mp3?key=dea9e4f8f932e9a1cf63fb4368239c01&request_event_id=f615f011-2447-4819-b2ea-261dcf46733f&timetoken=1734292162_2D238411A35E6AA8F2E9118FE0566858 HTTP/11" 200 63442918
INFO  [shared.podcast_downloader] Download complete.
DEBUG [httpx] load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG [httpx] load_verify_locations cafile='C:\\Users\\Administrator\\.virtualenvs\\podly_pure_podcasts-main-n1Rxt2gQ\\Lib\\site-packages\\certifi\\cacert.pem'
ERROR [app] Exception on /post/6f29b2e6fda4b799a6287a081cae1789.mp3 [GET]
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\app\routes.py", line 81, in download_post
    output_path = processor.process(post)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(podcast_processor.podcast_processor.PodcastProcessor.process) at 0x148b8c267a0>", line 32, in process
  File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\podcast_processor\podcast_processor.py", line 84, in process
    classification_dir = self.make_dirs(post, processed_audio_path)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(podcast_processor.podcast_processor.PodcastProcessor.make_dirs) at 0x148b8c26840>", line 50, in make_dirs
  File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\podcast_processor\podcast_processor.py", line 121, in make_dirs
    os.makedirs(processed_audio_dir, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'srv/Where Should We Begin? with Esther Perel'

=====

Let me know if this was another user error on my part or further bugs in the coding.

**Comment by reynold1** [comment]
Closed as resolved but opened new issue
