### ISSUE TITLE
Add a way to remove feeds from the web UI

### ISSUE THREAD

**Issue by frrad** [jdrbc/podly_pure_podcasts#46]
we should be a bit thoughtful about the UI of doing this. 

I think it would be bad to have a one click "remove" from the main page.

It would be better to have it be from the (as yet non existant) feed page, and maybe have some sort of confirmation popup to do the delete. Otherwise this is a bit of a footgun.

Also, we should think about the behavior wrt Posts. Should we cleanup posts when the feed is deleted? What happens when someone deletes a feed and then adds it back? Should we keep the old posts around and try to restore them when the feed is added back? If not, we need to watch out for collisions with the old data in the FS.

Anyone with design opinions please chime in. (@jdrbc ?)

**Comment by jdrbc** [comment]
I think it's okay to have a delete button in the main UI as long as there is a confirmation prompt. It should clear all downloads and drop all posts IMO. People might be deleting feeds to work around bugs or clear up storage so best to give them a fresh start.

**Comment by reynold1** [comment]
In my error testing, it would be helpful to have the option to delete from the website user interface instead of having to delete the database file in order to purge the previous loaded podcast

**Comment by reynold1** [comment]
Also, is the process of transcribing the podcast and generating the new ad free episode using FFmpeg reflected in the windows cmd window so the user is aware that the process is taking place?

**Comment by frrad** [comment]
> 
Also, is the process of transcribing the podcast and generating the new ad free episode using FFmpeg reflected in the cmd window so the user is aware of the current status of the process?

There are various log message that print throughout the process. You can read `podcast_processor.py` for the `logger.info` messages to get a feel for what you should see.
